//CommonJs, every file is a module (by default)
//Modules - Encapsulated code (only share minimum)

const names = require('./4-names')
const sayHi = require('./5-utils')
const data = require('./6-alternative')

console.log('')
console.log(data)
console.log(data.person)
console.log(data.person.name)
console.log(data.items)
console.log(data.items[0])
console.log('')
require('./7-minegrenade')
console.log('')
sayHi('Susan')
sayHi(names.john)
sayHi(names.peter)